#!/usr/bin/env node
/**
 * Generate the tool reference for the roblox-mcp-pro skill straight from the
 * compiled tool registrations (zod schemas + descriptions in dist/). The code
 * is the single source of truth — this file can never drift from it.
 *
 * Output: .agents/skills/roblox-mcp-pro/references/tools.md
 * Run: npm run docs (also part of prepublishOnly, so every release is current).
 */

import { writeFileSync, mkdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const { registerAllTools } = await import(
  new URL("../dist/tools/index.js", import.meta.url).href
);

// Duck-typed McpServer: capture every registration instead of serving them.
const tools = [];
const fakeServer = {
  registerTool(name, config, _handler) {
    tools.push({ name, config });
  },
};
registerAllTools(fakeServer);
if (tools.length === 0) {
  console.error("gen-docs: no tools captured — did registerAllTools change API?");
  process.exit(1);
}

/** Peel ZodOptional/ZodDefault/ZodNullable; report required-ness and default. */
function unwrap(zodType) {
  let required = true;
  let def;
  let description;
  let current = zodType;
  while (current?._def) {
    description ??= current.description;
    const tn = current._def.typeName;
    if (tn === "ZodOptional" || tn === "ZodNullable") {
      required = false;
      current = current._def.innerType;
    } else if (tn === "ZodDefault") {
      required = false;
      def = current._def.defaultValue();
      current = current._def.innerType;
    } else {
      break;
    }
  }
  description ??= current?.description;
  return { inner: current, required, def, description };
}

function typeLabel(zodType) {
  const def = zodType?._def;
  if (!def) return "unknown";
  switch (def.typeName) {
    case "ZodString":
      return "string";
    case "ZodNumber":
      return "number";
    case "ZodBoolean":
      return "boolean";
    case "ZodEnum":
      return def.values.map((v) => `'${v}'`).join(" | ");
    case "ZodArray":
      return `${typeLabel(unwrap(def.type).inner)}[]`;
    case "ZodRecord":
      return "object (map)";
    case "ZodObject":
      return "object";
    case "ZodUnion":
      return def.options.map((o) => typeLabel(unwrap(o).inner)).join(" | ");
    case "ZodUnknown":
    case "ZodAny":
      return "any";
    default:
      return (def.typeName ?? "unknown").replace(/^Zod/, "").toLowerCase();
  }
}

const pkg = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));

const lines = [
  `# roblox-mcp-pro tool reference (v${pkg.version})`,
  "",
  "<!-- AUTO-GENERATED by scripts/gen-docs.mjs from the compiled tool schemas.",
  "     Do not edit by hand — run `npm run docs` to regenerate. -->",
  "",
  `Exact parameters for all ${tools.length} tools. The SKILL.md covers when to use which tool;`,
  "this file is the per-parameter contract, generated from the same zod schemas the",
  "server validates with.",
  "",
];

for (const { name, config } of tools) {
  const readOnly = config.annotations?.readOnlyHint ? "read-only" : "mutating";
  lines.push(`## \`${name}\` — ${config.title} (${readOnly})`, "");
  if (config.description) lines.push(config.description.trim(), "");
  const shape = config.inputSchema ?? {};
  const entries = Object.entries(shape);
  if (entries.length === 0) {
    lines.push("Parameters: none.", "");
    continue;
  }
  lines.push("Parameters:", "");
  for (const [param, zodType] of entries) {
    const { inner, required, def, description } = unwrap(zodType);
    const bits = [typeLabel(inner)];
    bits.push(required ? "required" : "optional");
    if (def !== undefined) bits.push(`default ${JSON.stringify(def)}`);
    const desc = description ? ` — ${description}` : "";
    lines.push(`- \`${param}\` (${bits.join(", ")})${desc}`);
  }
  lines.push("");
}

const outDir = path.join(root, ".agents", "skills", "roblox-mcp-pro", "references");
mkdirSync(outDir, { recursive: true });
const outFile = path.join(outDir, "tools.md");
writeFileSync(outFile, lines.join("\n"));
console.log(`gen-docs: wrote ${path.relative(root, outFile)} (${tools.length} tools).`);
